name: test
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Audit URLs using Lighthouse
      uses: treosh/lighthouse-ci-action@v9
      with:
        urls: |
          https://www.meziantou.net
          https://www.meziantou.net/projects.htm
        budgetPath: ./budget.json
        uploadArtifacts: true